---
- name: create promtail config dir
  ansible.builtin.file:
    name: /etc/promtail
    state: directory
    owner: promtail
    group: promtail
  become: yes

- name: create promtmail config file
  ansible.builtin.template:
    src: promtail.yaml.j2
    dest: /etc/promtail/promtail.yaml
    owner: promtail
    group: promtail
    mode: '0640'
    force: no
  become: yes
